In [2]:
import numpy as np


In [4]:
v1 = np.array([1,2,3])
v2= np.array([4,5,6])

In [5]:
v1 * v2

array([ 4, 10, 18])

In [6]:
np.dot(v1, v2)


32

In [4]:
# dir(np)
np.linalg.norm(np.array([3, 4]))


5.0

In [13]:
A=np.array([[1,2],[3,4]])
Ai=np.linalg.inv(A)

A
Ai


array([[-2. ,  1. ],
       [ 1.5, -0.5]])

In [19]:
b=np.array([5,11])


In [26]:
x=np.dot(Ai, b)
x

array([1., 2.])